apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimus.fullname" . }}
  labels: {{- include "optimus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector: {{- include "optimus.selectorLabels" . | nindent 4 }}
